### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by Dy1ng0215** [LangChenCC/Sniffer#1]
![image](https://user-images.githubusercontent.com/75977513/220160022-8ec64e07-839d-4726-b557-101c8c06898e.png)
![image](https://user-images.githubusercontent.com/75977513/220163369-e1a5ac10-867a-4d2a-8b27-f3f5b680b310.png)
您好 我运行这个程序出现这样的错误，请问是什么问题呢？呜呜呜我一直解决不了

**Comment by LACHENNG** [comment]
能否有关错误更详细的内容，包括但不限于
1.  运行环境（visual studio 版本）
2. 出错文件名
3. 编译错误详情

**Comment by LACHENNG** [comment]
更新了仓库，git clone 重新编译运行
